version: "3.3"

services:
  nextjs:
    container_name: nextjs
    ports:
      - "3000:3000"
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next

  nginx:
    container_name: nginx
    build:
      context: ./api/docker/nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - nextjs

  php-fpm:
    container_name: php-fpm
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - 'mysql'

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "Drom.Review"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: { }