version: "3.3"

services:
  nextjs:
    ports:
      - "80:3000"
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next